//
// Generated file, do not edit! Created by opp_msgtool 6.3 from applications/MyTaskChunk.msg.
//

#ifndef __INET_MYTASKCHUNK_M_H
#define __INET_MYTASKCHUNK_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0603
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif


namespace inet {

class MyTaskChunk;

}  // namespace inet

// cplusplus {{
 #include "inet/common/INETDefs.h" 
// }}

#include "inet/common/packet/chunk/Chunk_m.h" // import inet.common.packet.chunk.Chunk


namespace inet {

/**
 * Class generated from <tt>applications/MyTaskChunk.msg:20</tt> by opp_msgtool.
 * <pre>
 * class MyTaskChunk extends FieldsChunk
 * {
 *     int RequiredCPUCycles;
 *     simtime_t creationTime;
 * 
 * }
 * </pre>
 */
class MyTaskChunk : public ::inet::FieldsChunk
{
  protected:
    int RequiredCPUCycles = 0;
    ::omnetpp::simtime_t creationTime = SIMTIME_ZERO;

  private:
    void copy(const MyTaskChunk& other);

  protected:
    bool operator==(const MyTaskChunk&) = delete;

  public:
    MyTaskChunk();
    MyTaskChunk(const MyTaskChunk& other);
    virtual ~MyTaskChunk();
    MyTaskChunk& operator=(const MyTaskChunk& other);
    virtual MyTaskChunk *dup() const override {return new MyTaskChunk(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual int getRequiredCPUCycles() const;
    virtual void setRequiredCPUCycles(int RequiredCPUCycles);

    virtual ::omnetpp::simtime_t getCreationTime() const;
    virtual void setCreationTime(::omnetpp::simtime_t creationTime);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const MyTaskChunk& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, MyTaskChunk& obj) {obj.parsimUnpack(b);}


}  // namespace inet


namespace omnetpp {

template<> inline inet::MyTaskChunk *fromAnyPtr(any_ptr ptr) { return check_and_cast<inet::MyTaskChunk*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __INET_MYTASKCHUNK_M_H

