//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Lesser General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
// 
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Lesser General Public License for more details.
// 
// You should have received a copy of the GNU Lesser General Public License
// along with this program.  If not, see http://www.gnu.org/licenses/.
// 

#ifndef __MYPROJECTANDTUTORIAL_RESOURCEALLOCATORAPP_H_
#define __MYPROJECTANDTUTORIAL_RESOURCEALLOCATORAPP_H_

#include <omnetpp.h>
#include <inet/applications/base/ApplicationBase.h>
#include "inet/transportlayer/contract/udp/UdpSocket.h"
#include "MyTaskChunk_m.h"

using namespace omnetpp;
using namespace inet;

#include <pybind11/pybind11.h>
#include <pybind11/embed.h>
#include <pybind11/stl.h>
namespace py = pybind11;

/**
 * Better than a class since I need to access and modify everything.
 */
struct Task : public cObject
{
    int requiredCPUCycles; // The number of CPU cycles required to process/compute a task.
    int allocatedCPUFrequency; // The number of CPU cycles that will be processed in a single second - the speed of processing the task.
    double executionTime; // The time it will take for the task to be processed on the edge server. This variable is to be used for calculating when a self-message should be scheduled.


    // Variables Mainly for Statistics
    simtime_t creationTime; // The time at which the task was created and sent to the edge server from the mobile device.
    simtime_t completionTime; // The time at which the task finished executing on the edge server.

    simtime_t arrivalTime; // The time at which the task entered the edge server - just before it is allocated resources.
    simtime_t totalServiceTime; // In seconds, the total duration of the task's queueing + execution/processing time.
    simtime_t communicationDelay; // In seconds, the difference in time between the task being created and arriving at the edge server.

    simtime_t startQueueTime; // The time at which the task entered the queue.
    simtime_t endQueueTime; // The time at which the task left the queue.
    simtime_t totalQueueTime; // In seconds, the total duration of time the task was in the queue.

    simtime_t latency; // In seconds, the difference in time between the task being sent to the edge server and it finishing being processed.
    double energyConsumption; // The amount of energy (in an undefined unit) that was consumed to process the task.

    // Resource Allocation Specific
    std::vector<double> state; // The state space used to inform the CPU frequency that was to be allocated to the task.
    double logProbability; // The log probability given to the task for the action taken (CPU frequency allocated).
    double rawAction; // The raw action PPO produced prior to constraints.
};


/**
 * MEC Resource Allocator application.
 *
 * This class is responsible for the allocation of MEC server resources within the
 * simulation. As described with the methodology of the dissertation, the server allocates
 * a certain CPU frequency (given in MHz) towards a task generated by a user device. If at
 * any time the number of tasks within the MEC's queue exceeds 50, subseqeuent tasks are
 * offloaded to the distant cloud server.
 *
 * There are a possible of 3 different allocation policies that can be
 * chosen for the simulation and is specified within the omnetpp.ini file, including
 * a greedy heuristic, a PPO agent and a random allocator.
 *
 * Rather than list the entire functionality of this application (which cannot be done concisely),
 * I would encourage the reader to refer to section 3.1 (System Architecture) of the dissertation
 * for more detail.
 *
 * In addition to handling resource, the class is responsible for creating and subsequently deleting
 * a Python interpreter should the PPO agent be chosen for allocating resources. The class also tracks
 * and "emits" all the key evaluative metrics used within the dissertation.
 */
class ResourceAllocatorApp : public ApplicationBase, UdpSocket::ICallback
{
  protected:
    // Resource Allocation
    int maxCPUCapacity = 10000; // The maximum capacity of the MEC server (measured in MHz to avoid overflow errors).
    int currentCapacity = 0; // The capacity occupied of the MEC server at a given time (measured in MHz).
    cQueue queue; // The FIFO queue used to hold tasks waiting for execution.
    int maxQueueLength = 50; // The maximum length of the FIFO queue.
    int resourceAllocatorAlgorithm = 0; // The algorithm to be used for allocating CPU frequency.

    int episodeLength; // The number of time-steps the episode requires to finish.

    // Python/Pybind-related
    bool pythonAllocatorStarted = false;

    // MEC Port Parameters
    int localPort = -1;
    L3Address destAddress;
    std::string destAddressStr;
    int destPort = -1;

    // Statistics
    int packetsReceived = 0;
    int tasksProcessed = 0;
    int tasksProcessing = 0;
    int cloudOffloadedTasks = 0;

    simsignal_t latencySignal;
    simsignal_t resourceUtilisationSignal;
    simsignal_t energyConsumptionSignal;
    simsignal_t tasksProcessedSignal;
    simsignal_t queueLengthSignal;
    simsignal_t parallelTasksSignal;
    simsignal_t cloudOffloadedTasksSignal;

    UdpSocket socket; // Requires a socket to bind the application to.

    void processTask(Task *task);
    double getTimeToExecute(double cpuCyclesRequired, double allocatedCPUCycles);
    void allocateResources(Task *task);
    void endTaskExecution(cMessage *msg);
    void updateQueue();
    double getResourceUtilisation();
    int getTotalCyclesInQueue();

    void sendPacket(Packet * packet);

    // Allocation Algorithms
    int staticAllocation(int requiredCycles);
    int PPOAllocation(Task *task);
    int randomAllocation();

    virtual void finish() override;
    virtual void initialize(int stage) override;
    virtual void handleMessageWhenUp(cMessage *msg) override;

    virtual void refreshDisplay() const override;

    // Inheriting UdpSocket::ICallback requires these 3 methods.
    virtual void socketDataArrived(UdpSocket *socket, Packet *packet) override;
    virtual void socketErrorArrived(UdpSocket *socket, Indication *indication) override;
    virtual void socketClosed(UdpSocket *socket) override;

    // Inheriting ApplicationBase requires these 3 methods.
    virtual void handleStartOperation(LifecycleOperation *operation) override;
    virtual void handleStopOperation(LifecycleOperation *operation) override;
    virtual void handleCrashOperation(LifecycleOperation *operation) override;

  public:
    virtual int numInitStages() const override { return NUM_INIT_STAGES; }
};

#endif
