[General]
description = Simple sim where two nodes communicate wirelessly.
network = ResourceNetwork
#sim-time-limit = 1000s
seed-set = 1
*.edgeServer.app[0].maxCPUCapacity = 10000
#*.edgeServer.app[0].resourceAllocatorAlgorithm = 2 # Was 1
*.edgeServer.app[0].episodeLength = 10000 # Was 512

*.*.ipv4.arp.typename = "GlobalArp"

# Mobile Device Configuration
*.md*[*].numApps = 1
*.md*[*].app[0].typename = "TrafficGenerator"	# UdpEchoApp will send back packets; was UdpBasicApp
*.md*[*].app[0].destAddresses = "edgeServer" # "hostB"
*.md*[*].app[0].destPort = 5000 # HTTP Request
*.md*[*].app[0].messageLength = 1024B
*.md*[*].app[0].sendInterval = exponential(35ms)
*.md*[*].app[0].packetName = "TaskData"
*.mdMobilePhone[*].app[0].minRequiredCPUCycles = 200
*.mdMobilePhone[*].app[0].maxRequiredCPUCycles = 500
*.mdAutonomousVehicle[*].app[0].minRequiredCPUCycles = 100
*.mdAutonomousVehicle[*].app[0].maxRequiredCPUCycles = 500
*.mdIoTDevice[*].app[0].minRequiredCPUCycles = 60
*.mdIoTDevice[*].app[0].maxRequiredCPUCycles = 100
*.mdARVRUser[*].app[0].minRequiredCPUCycles = 300
*.mdARVRUser[*].app[0].maxRequiredCPUCycles = 700

# Edge Server Configuration
*.edgeServer*.numApps = 1
*.edgeServer*.app[0].typename = "ResourceAllocatorApp" # Acts as a sink app; Was "UdpSink"
*.edgeServer*.app[0].localPort = 5000
*.edgeServer*.app[0].destAddress = "cloudServer"
*.edgeServer*.app[0].destPort = 5000 # HTTP Request

# Cloud Server Configuration
*.cloudServer.numApps = 1
*.cloudServer.app[0].typename = "UdpSink"
*.cloudServer.app[0].localPort = 5000

# WLAN Configuration
*.md*[*].wlan[0].typename = "AckingWirelessInterface"
*.md*[*].wlan[0].mac.useAck = false
*.md*[*].wlan[0].mac.fullDuplex = false
#*.md*[*].wlan[0].radio.transmitter.communicationRange = 500m
*.md*[*].wlan[0].mac.headerLength = 23B

*.md*[*].wlan[0].radio.typename = "ApskRadio"
*.md*[*].wlan[0].radio.centerFrequency = 2GHz # Carrier Frequency
#*.md*[*].wlan[0].radio.bandwidth = 2MHz
#*.md*[*].wlan[0].radio.receiver.bandwidth = 20MHz
*.md*[*].wlan[0].radio.transmitter.power = 10mW		# A strong enough signal so that the packet may reach the base station from a distance away.
*.md*[*].wlan[0].radio.transmitter.preambleDuration = 10us
*.md*[*].wlan[0].radio.transmitter.headerLength = 8B
*.md*[*].wlan[0].radio.receiver.sensitivity = -85dBm
*.md*[*].wlan[0].radio.receiver.energyDetection = -85dBm
*.md*[*].wlan[0].radio.receiver.snirThreshold = 4dB

# Base Station Configuration
*.baseStation.forwarding = true
*.baseStation*.wlan[0].typename = "AckingWirelessInterface"
*.baseStation*.wlan[0].mac.useAck = false
*.baseStation*.wlan[0].mac.fullDuplex = false
#*.baseStation*.wlan[0].radio.transmitter.communicationRange = 500m
*.baseStation*.wlan[0].mac.headerLength = 23B

*.baseStation*.wlan[0].radio.typename = "ApskRadio"
*.baseStation*.wlan[0].radio.centerFrequency = 2GHz
*.baseStation*.wlan[0].radio.transmitter.power = 10mW
*.baseStation*.wlan[0].radio.transmitter.preambleDuration = 10us
*.baseStation*.wlan[0].radio.transmitter.headerLength = 8B
*.baseStation*.wlan[0].radio.receiver.sensitivity = -90dBm
*.baseStation*.wlan[0].radio.receiver.energyDetection = -85dBm
*.baseStation*.wlan[0].radio.receiver.snirThreshold = 4dB

# Cloud Server Configuration
*.cloudServer*.wlan[0].typename = "AckingWirelessInterface"
*.cloudServer*.wlan[0].mac.useAck = false
*.cloudServer*.wlan[0].mac.fullDuplex = false
#*.baseStation*.wlan[0].radio.transmitter.communicationRange = 500m
*.cloudServer*.wlan[0].mac.headerLength = 23B

*.cloudServer*.wlan[0].radio.typename = "ApskRadio"
*.cloudServer*.wlan[0].radio.centerFrequency = 2GHz
*.cloudServer*.wlan[0].radio.transmitter.power = 10mW
*.cloudServer*.wlan[0].radio.transmitter.preambleDuration = 10us
*.cloudServer*.wlan[0].radio.transmitter.headerLength = 8B
*.cloudServer*.wlan[0].radio.receiver.sensitivity = -85dBm
*.cloudServer*.wlan[0].radio.receiver.energyDetection = -85dBm
*.cloudServer*.wlan[0].radio.receiver.snirThreshold = 4dB

**.wlan[0].radio.bandwidth = 20MHz
**.wlan[0].radio.receiver.bandwidth = 20MHz

#*.host*.**.bitrate = 1Mbps
*.baseStation*.wlan[0].bitrate = 100Mbps # Could be what I alter to achieve 6G?
#*.mdMobilePhone.wlan[0].bitrate = 1Mbps
*.md**.wlan[0].bitrate = 100Mbps

*.cloudServer.wlan[0].bitrate = 100Mbps

# Radio Configuration
*.radioMedium.backgroundNoise.power = -120dBm # changed to -120 from -90
*.radioMedium.backgroundNoise.centerFrequency = 2GHz
*.radioMedium.backgroundNoise.bandwidth = 20MHz 	# Commenting out hasn't made a difference

# Limit the medium's calculation range to save CPU and prevent errors
*.radioMedium.mediumLimitCache.centerFrequency = 2GHz
*.radioMedium.mediumLimitCache.bandwidth = 20MHz
*.radioMedium.mediumLimitCache.minRelativePower = -110dB # Signals below this are ignored
*.radioMedium.**ignorePartialInterference = true

#*.radioMedium.bandwidth = 10GHz
# Use MAC address filter to avoid sending to irrelevant devices on the network; from https://inet.omnetpp.org/docs/users-guide/ch-transmission-medium.html#overview
*.radioMedium.macAddressFilter = true

# Visualiser Configuration
#**.radio.displayCommunicationRange = true
#*.visualizer.mediumVisualizer.displaySignals = true
*.visualizer.physicalLinkVisualizer.displayLinks = true
*.visualizer.physicalLinkVisualizer.packetFilter = "TaskData"
*.visualizer.mobilityVisualizer.displayVelocities = true
*.visualizer.mobilityVisualizer.displayMovementTrails = true


[Config GeneralWithMobility]
description = Adds mobility to the mobile devices for each of the simulation scenarios. This config has been separated from the main one, so I can easily remove for testing or if I don't want to include it anymore.
extends = General

*.md*[*].mobility.typename = "LinearMobility"
*.md*[*].mobility.initFromDisplayString = false
*.md*[*].mobility.initialX = uniform(50m, 950m)
*.md*[*].mobility.initialY = uniform(50m, 950m)
*.md*[*].mobility.constraintAreaMinX = 0m
*.md*[*].mobility.constraintAreaMaxX = 1000m
*.md*[*].mobility.constraintAreaMinY = 0m
*.md*[*].mobility.constraintAreaMaxY = 1000m

*.mdMobilePhone[*].mobility.speed = 3mps
*.mdAutonomousVehicle[*].mobility.speed = 20mps
*.mdIoTDevice[*].mobility.speed = 3mps
*.mdARVRUser[*].mobility.speed = 1mps

[Config NonHeterogeneousTaskSizes]
description = Removes IoT devices, AR/VR users and heteregeneous task sizes. Returns the environment back to 15 MDs and 10 AVs.
extends = GeneralWithMobility

ResourceNetwork.numberOfMobilePhones = 15
ResourceNetwork.numberOfAutonomousVehicles = 10
ResourceNetwork.numberOfIoTDevices = 0
ResourceNetwork.numberOfARVRUsers = 0

*.md*[*].app[0].minRequiredCPUCycles = 100
*.md*[*].app[0].maxRequiredCPUCycles = 500

[Config LowLoad_25]
description = Adjusting the send interval of the mobile devices to reflect a low load (25%) of the edge server's capacity.
extends = GeneralWithMobility
*.md*[*].app[0].sendInterval = exponential(3000ms)

[Config MediumLoad_50]
description = Adjusting the send interval of the mobile devices to reflect a medium load (50%) of the edge server's capacity.
extends = GeneralWithMobility
*.md*[*].app[0].sendInterval = exponential(1500ms)

[Config MediumHighLoad_75]
description = Adjusting the send interval of the mobile devices to reflect a medium-high load (75%) of the edge server's capacity.
extends = GeneralWithMobility
*.md*[*].app[0].sendInterval = exponential(1000ms)

[Config High_100]
description = Adjusting the send interval of the mobile devices to reflect a high load (100%) of the edge server's capacity.
extends = GeneralWithMobility
*.md*[*].app[0].sendInterval = exponential(750ms)

[Config Overloaded_150]
description = Adjusting the send interval of the mobile devices to reflect a high load (150%) of the edge server's capacity.
extends = GeneralWithMobility
*.md*[*].app[0].sendInterval = exponential(500ms)

[Config PPOTraining]
description = Adjusting the number of mobile devices to 1, the send interval of the mobile device and episode length to train the PPO algorithm on a moderate load.
extends = GeneralWithMobility
seed-set = ${repetition}
#seed-set = 1
repeat = 1000
ResourceNetwork.numberOfMobilePhones = 0
ResourceNetwork.numberOfAutonomousVehicles = 1
ResourceNetwork.numberOfIoTDevices = 0
ResourceNetwork.numberOfARVRUsers = 0

# Alter the task sizes to match the lowest and highest potentially requested by a device.
*.mdAutonomousVehicle[*].app[0].minRequiredCPUCycles = 60
*.mdAutonomousVehicle[*].app[0].maxRequiredCPUCycles = 700

*.edgeServer.app[0].resourceAllocatorAlgorithm = 1
*.edgeServer.app[0].episodeLength = 512 # Was 512
*.md*[*].app[0].sendInterval = exponential(60.8ms) # 62.5794% static, 1 device, 512 tasks; 10k = 66.4755%.
# 48ms = 78.8613% on the static algorithm for 1 device, 512 tasks ([60,700]);
#*.md*[*].app[0].sendInterval = exponential(48ms) # Approximately, 62.3137% on the static algorithm for 1 device, 512 tasks ([100,500]); 10k tasks = 65.6321%. That is, on the the OG mobile device layout.
# Exponential 50ms = Approximately, 63.639% on the static algorithm for 1 device, 512 tasks; 10k tasks = 63.7552%; this could be changed for uniform distribution for more variability, like [50,70].

[Config Basic]
description = A very basic simulation with just 1 device so I can test out changes and different allocations more easily. I also don't use mobility either for an even simpler simulation.
extends = General
ResourceNetwork.numberOfMobilePhones = 0
ResourceNetwork.numberOfAutonomousVehicles = 1
*.edgeServer.app[0].resourceAllocatorAlgorithm = 2
*.edgeServer.app[0].episodeLength = 10000 # Was 512
*.md*[*].app[0].sendInterval = exponential(48ms)
